### ISSUE TITLE
Sounds & Game Mode

### ISSUE THREAD

**Issue by BeratNzp** [Maxximou5/csgo-deathmatch#128]
Hey,

1) Which mode should I choose start the server ?
Classic Casual: (+game_type 0 +game_mode 0)
or:
Deathmatch: (+game_type 1 +game_mode 2)

2) Should I use dm_enable_valve_deathmatch 1 ?

3) If I choose "Casual", everbody was see their team players behind of walls. And FF wasnt work.
If I choose "Deathmatch", Nobody was see their team players behind of walls and FF was work but, When someone leave the server, his avatar stayed player menu on the top of screen still. So this mode is better than "casual" but, I don't want to "Spawn Sounds" "Domination Sounds" etc. What can I do for this, I researched your script and tried to change somethings on 1942. and 1943. lines. But didnt change anything on server.

Thanks so much.

**Comment by borzaka** [comment]
I use with casual, because I use a rank plugin, which print out points based on kills, which would interfere with the Valve Deathmatch points.
I think you should only use dm_enable_valve_deathmatch 1 if you using the official deatchmatch mode.

I have no such problems. Are you sure you installed the latest version and every config?
