### ISSUE TITLE
Player can't see their skins when spawned on the other team

### ISSUE THREAD

**Issue by MajorErection** [Maxximou5/csgo-deathmatch#18]
Players playing on CT side can't see their AK skins etc, and vice versa.

They have to be spawned the respective teams to see their weapon skins.

**Comment by Maxximou5** [comment]
I'll look into it. I've done this before but it caused a lot of problems for third party plugins that hook into giving, changing, or editing the weapon. Though since Valve bans your server now for doing any of that, I might add it back in.

**Comment by MajorErection** [comment]
@Maxximou5 Valve only banned official skins not community ones if I'm not mistaken so it would still affect third party plugins.
Probably not your concern but does Sourcemod have some kind of plugin priority thingy? Maybe then you can set whatever you're doing as a lower priority so that if there are any third party plugins that would alter the weapon would override whatever you're doing.

I am no programmer so I might just be talking out of my ass so please go easy on me :P

**Comment by Maxximou5** [comment]
They'll ban you for pretty much anything they can, so I am hesitant to make a release or change that would get people's server banned. I know recently servers have been banned for the most ridiculous changes, such as changing the indexing of the weapon (e.g. making a deagle as an awp or vice versa). So I am a bit hesitant, but I'll put the code in and ask to see if it gets banned, if it doesn't, I'll release it as an optional cvar.

**Comment by MajorErection** [comment]
Wow that I didn't know, anyways if you need any help testing let me know, I'll try to do whatever I can to help

**Comment by MajorErection** [comment]
@Maxximou5 Why not just release it as another module of it's own, so that would prevent people from accidentally having it on and getting wrongfully banned if Valve decides to make what you're doing illegal.

Again, this is just a suggestion :) Peace

**Comment by BrutalCSEjziponken** [comment]
Maybe this can bring some light:
https://forums.alliedmods.net/showpost.php?p=2396736&postcount=50

**Comment by splewis** [comment]
I willing to make a pull request to do this, since "deathmatch goes advanced" isn't likely to be maintained anymore. The easiest way to do this to set the player's team to the team that the weapon belongs to (e.g. if giving an AK set the player team to T, then swap them back to CT if needed). This is what [multi1v1](https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/multi1v1/weaponlogic.sp#L143) does.

From a quick glance, just wrapping the GivePlayerItem calls around [here](
https://github.com/Maxximou5/csgo-deathmatch/blob/master/scripting/deathmatch.sp#L2186) would do it. Not sure whether you'd want the weapon->team data hardcoded into the plugin or read from a config file.

**Comment by Maxximou5** [comment]
@splewis That would be great and highly appreciated. I would probably want it to be read from the the same configuration file (deathmatch.ini). Though I am open to suggestions and different routes, as we would want the easiest path but also the best option for configuration. I want to give users options, but also want to keep the plugin as simple as possible, as that's what separates this from h3bus's. Let me know your thoughts, and I appreciate the help.
