### ISSUE TITLE
[idea ] Give random grenade to player on respawn

### ISSUE THREAD

**Issue by melkor217** [Maxximou5/csgo-deathmatch#28]
Subj. Could somebody plz implement this? :3

**Comment by Maxximou5** [comment]
This isn't something I will do, because it would require a lot of work I'm just not willing to do. However, if someone else wants to do this, that would be great.
It would require: 
- Adding in kv entries for which possible grenades are allowed to spawn with.
- Add cvar for allowing player to spawn with random grenade.
- Cvar check for on spawn equip for whether the cvar is enabled.
- Check the values for allowed grenades, getrandom value and equip grenade.
- Combine compatibility with already existing equip grenades on spawn. 
- Combine compatibility with already existing on explosion event to return new grenade.
