### ISSUE TITLE
Nuke spawn points are broken

### ISSUE THREAD

**Issue by melkor217** [Maxximou5/csgo-deathmatch#29]
... since de_nuke was remade :(

**Comment by melkor217** [comment]
Btw, de_cache spawns are broken as well.

**Comment by Maxximou5** [comment]
Spawn points are always going to break at some point, because Valve updates the maps. I won't update the spawn points, that's up to people who use them. The plugin has an easy to use system to fix and edit the spawn points. Just fix them and do a pull request from GitHub. The only and probably last time I will ever edit the spawn points is when v2.1.0 comes out, which will include (all, T, or CT) team based spawns.

Closing this because it's not something to be fixed, only maintained by others.

**Comment by melkor217** [comment]
I just want to ensure that my spawn points has acceptable density over the map. After some testing i'll make a pull request for this.
