### ISSUE TITLE
Respawning with same weapon isn't allowed

### ISSUE THREAD

**Issue by yomom958** [Maxximou5/csgo-deathmatch#36]
I've changed the deatmatch.ini file so that it is only an m4/ak only server. Its FFA as well, but it doesn't allow me to select option 2 and 3 when i open up the gun menu.

I'm using mp_ignore_win_condition 1 as well as mp_roundtime 60 and mp_roundtime_defuse 60

Do I need to add pistols in order to make selecting the same weapons viable again?

**Comment by faarecsgo** [comment]
I had the same experience when setting up my server. Maxximou5 is aware of it.  
The issue is caused by the lack of secondary weapon. The work around you can do is to put all secondary weapons to 0 but put "random" to -1. Players will only be able to click random but they won't get anything. Then they will be able to use the options "Same weapons" and "Same weapons every round".
