### ISSUE TITLE
P2000 Deagle sound 

### ISSUE THREAD

**Issue by LELS555** [Maxximou5/csgo-deathmatch#38]
Hey,

how can i fix the issue with the P2000 having the Deagle sound ?

**Comment by Maxximou5** [comment]
The only method available to give players the hkp_2000 caused the weapon to believe it was a deagle. As a result, this was removed and players much select the hkp_2000 in their loadout inventory to have it equipped properly. This is an unfortunate circumstance due to the only other method available to fixing the issue would cause a GSLT ban.

Blame Valve.

**Comment by MajorErection** [comment]
I know almost nothing about sourcepawn but did you change the way the players get their guns from 2.0.5? Because I have servers running 2.0.5 and the p2k works fine. Hopefully this helps :)
