### ISSUE TITLE
P2000 bug. 

### ISSUE THREAD

**Issue by Sevrik** [Maxximou5/csgo-deathmatch#42]
Hello,
I've updated your plugin for 2.0.7, but the problem is not solved with p2000.

I made a menu with only handguns, but when choosing P2000 given usp_silencer.
Please tell me what could be the problem?

PS: sorry for my english, it's online translator. :)

**Comment by MajorErection** [comment]
The player has to equip p2000 in their loadout menu in order to choose p2000 in the deathmatch plugin. I'm using 2.0.7 and there isn't any issues with the pistols. Hope this helps.

**Comment by Maxximou5** [comment]
As @MajorErection has mentioned, there is no way for the p2000 to be equipped with side effects. Either a GSLT ban or it taking on the properties of the AWP. For now, you will just have to have the p2000 equipped if you want it to be spawned. You will have to convince VALVe to lift these restrictions in order for me to be able to apply them. If you are bypassing or using bought tokens, you will have to ask someone else to add it in, because it's not something I will do unfortunately.

**Comment by Sevrik** [comment]
Thank you very much.
